import { ContextProvider } from '@/contexts/provider'
import '../styles/globals.css'
// eslint-disable-next-line camelcase
import { Roboto_Flex } from 'next/font/google'

const roboto = Roboto_Flex({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
  style: 'normal',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  )
}
